# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Set command timeout to prevent hanging
command_timeout = 1000

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
# ~/.config/starship.toml

[aws]
format = 'on [$symbol$profile]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

[line_break]
disabled = false

[localip]
ssh_only = true
format = '@[$localipv4](bold red) '
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bold dimmed green'
